//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.Ipasbr.Services.Tests.FormatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.sixeyed.ipasbr", ConfigurationName="FormatService.IFormatService")]
    public interface IFormatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sixeyed.ipasbr/IFormatService/ReverseString", ReplyAction="com.sixeyed.ipasbr/IFormatService/ReverseStringResponse")]
        string ReverseString(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormatServiceChannel : Sixeyed.Ipasbr.Services.Tests.FormatService.IFormatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormatServiceClient : System.ServiceModel.ClientBase<Sixeyed.Ipasbr.Services.Tests.FormatService.IFormatService>, Sixeyed.Ipasbr.Services.Tests.FormatService.IFormatService {
        
        public FormatServiceClient() {
        }
        
        public FormatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReverseString(string input) {
            return base.Channel.ReverseString(input);
        }
    }
}
